let API = window.APP_CONFIG.API_BASE_URL.replace(/\/$/, ''), useProxy = false;
let currentConversation = null, editingId = null;
const $ = s => document.querySelector(s);
async function api(path, options = {}) { const url = useProxy ? `${API}?path=${encodeURIComponent(path)}` : API + path; const r = await fetch(url, {headers:{'Content-Type':'application/json'}, ...options}); if (!r.ok) throw new Error((await r.json().catch(()=>({detail:r.statusText}))).detail); return r.status === 204 ? null : r.json(); }
function escapeHtml(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function addMessage(role, text, cls=''){ $('#messages').insertAdjacentHTML('beforeend', `<article class="message ${role} ${cls}">${escapeHtml(text)}</article>`); $('#messages').scrollTop=99999; }
async function loadSummary(){const s=await api('/api/data/summary'); $('#summary').innerHTML=`<strong>${s.count}개 관측치</strong><br>${s.period_start||'-'} ~ ${s.period_end||'-'}<br>평균 ${s.average} · 최소 ${s.minimum} · 최대 ${s.maximum}<br><strong>${s.trend_detail}</strong>`}
async function loadData(){const rows=await api('/api/data');const list=$('#data-list');list.innerHTML='';rows.slice().reverse().forEach(x=>{const el=$('#row-template').content.firstElementChild.cloneNode(true);el.querySelector('.date').textContent=x.date;el.querySelector('.value').textContent=x.value;el.querySelector('.memo').textContent=x.memo;el.querySelector('.edit').onclick=()=>beginEdit(x);el.querySelector('.delete').onclick=async()=>{if(confirm('이 데이터를 삭제할까요?')){await api('/api/data/'+x.id,{method:'DELETE'});await refreshData()}};list.append(el)})}
async function refreshData(){await Promise.all([loadData(),loadSummary()])}
function beginEdit(x){editingId=x.id;$('#data-date').value=x.date;$('#data-value').value=x.value;$('#data-memo').value=x.memo;$('#data-submit').textContent='저장';$('#cancel-edit').hidden=false}
function cancelEdit(){editingId=null;$('#data-form').reset();$('#data-submit').textContent='추가';$('#cancel-edit').hidden=true}
async function loadHistory(){const rows=await api('/api/conversations');const h=$('#history');h.innerHTML='';rows.forEach(x=>{const row=document.createElement('div');row.className='history-row';const open=document.createElement('button');open.className='secondary';open.textContent=x.title;open.onclick=()=>openConversation(x.id);const del=document.createElement('button');del.className='danger';del.textContent='×';del.onclick=async()=>{await api('/api/conversations/'+x.id,{method:'DELETE'});if(currentConversation===x.id) $('#new-chat').click();await loadHistory()};row.append(open,del);h.append(row)})}
async function openConversation(id){const c=await api('/api/conversations/'+id);currentConversation=id;$('#messages').innerHTML='';c.messages.forEach(m=>addMessage(m.role,m.content));}
$('#chat-form').onsubmit=async e=>{e.preventDefault();const q=$('#question').value.trim();if(!q)return;addMessage('user',q);$('#question').value='';const loading=document.createElement('div');loading.className='loading';loading.textContent='AI가 데이터 요약을 읽고 있습니다…';$('#messages').append(loading);try{const r=await api('/api/chat',{method:'POST',body:JSON.stringify({message:q,conversation_id:currentConversation})});loading.remove();currentConversation=r.conversation_id;addMessage('assistant',r.answer);await loadHistory()}catch(err){loading.remove();addMessage('assistant','오류: '+err.message)}};
$('#data-form').onsubmit=async e=>{e.preventDefault();const body={date:$('#data-date').value,value:Number($('#data-value').value),memo:$('#data-memo').value};await api(editingId?'/api/data/'+editingId:'/api/data',{method:editingId?'PUT':'POST',body:JSON.stringify(body)});cancelEdit();await refreshData()};$('#cancel-edit').onclick=cancelEdit;$('#new-chat').onclick=()=>{currentConversation=null;$('#messages').innerHTML='';addMessage('assistant','새 대화를 시작했습니다. 저장된 데이터 요약을 기반으로 질문에 답하겠습니다.')};
(async()=>{try{const config=await fetch('/api/config').then(r=>r.ok?r.json():null);if(config?.apiBaseUrl){ API=config.apiBaseUrl.replace(/\/$/, ''); useProxy=Boolean(config.proxy); }}catch(_){}try{const health=await api('/');$('#storage-status').textContent=health.storage==='firestore'?'Firestore 연결':'데모 메모리 모드';await Promise.all([refreshData(),loadHistory()])}catch(e){$('#storage-status').textContent='API 연결 실패';console.error(e)}})();
